[project]
name = "arena-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.arena-pass]
path = "contracts/arena-pass.clar"
depends_on = []

[contracts.resale-manager]
path = "contracts/resale-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
